commitment = "0x0" # placeholder, computed by prover
shot_x = "5"
shot_y = "3"
declared_hit = "1"
width = "10"
height = "10"
fleet_count = "5"
fleet_lens = ["5","4","3","3","2","0","0","0","0","0"]
game_id = "1"
salt = "123456789"
xs = ["0","2","5","7","9","0","0","0","0","0"]
ys = ["0","1","3","6","9","0","0","0","0","0"]
dirs = ["0","1","0","1","0","0","0","0","0","0"]


